# Generated by Django 6.0.3 on 2026-03-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bloodrequest",
            old_name="units_required",
            new_name="units_needed",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="hospital",
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="hospital_name",
            field=models.CharField(default="General Hospital", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="request_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
